### ISSUE TITLE
Is rdf data duplicated in the triple store?

### ISSUE THREAD

**Issue by delahousse** [DOREMUS-ANR/knowledge-base#31] opened 2017-03-20 11:23 UTC
Hello, on this query we find 2 lines for each results. We wonder if the triples are doubled in the data base ? if not what could be the reason ?
Jean
[Query_scores_published_in_vienna.txt](https://github.com/DOREMUS-ANR/knowledge-base/files/854589/Query_scores_published_in_vienna.txt)

**Comment by pasqLisena** [comment] 2017-03-20 14:44
I put the query here for trackability:

```turtle
SELECT *
WHERE {
?F30_Publication_Event 	a efrbroo:F30_Publication_Event;
			 ecrm:P7_took_place_at "Vienne";
		         ecrm:P4_has_time-span ?P4_has_time_span.

?P4_has_time_span 	ecrm:P80_end_is_qualified_by ?P80_end_is_qualified_by;
			ecrm:P79_beginning_is_qualified_by ?P79_beginning_is_qualified_by.
FILTER (?P80_end_is_qualified_by < "1899-12-31"^^xsd:dateTime)
FILTER (?P79_beginning_is_qualified_by > "1800-01-01"^^xsd:dateTime)

?F14_Individual_Work 	mus:U4_had_princeps_publication ?F30_Publication_Event;
			 efrbroo:R9_is_realised_in ?F22_Self_Contained_Expression.

?F22_Self_Contained_Expression mus:U70_has_title ?F22_Self_Contained_Expression_TITLE.
FILTER regex(lang(?F22_Self_Contained_Expression_TITLE), "fr")

?F28_Expression_Creation 	efrbroo:R17_created ?F22_Self_Contained_Expression;
ecrm:P9_consists_of/ecrm:P14_carried_out_by/ecrm:P131_is_identified_by ?F22_Self_Contained_Expression_COMPOSER_NAME.

} ORDER BY (?P79_beginning_is_qualified_by)
```

I tried to remove slices of the query, and it seems that the duplicated part is the last one: 
```turtle
SELECT *
WHERE {
?a ecrm:P14_carried_out_by ?b .
?b ecrm:P131_is_identified_by ?F22_Self_Contained_Expression_COMPOSER_NAME.
} LIMIT 100
```

This can be caused by the fact that we load the info on the composer name twice: when we parse the artist file and when we find it as composer. Virtuoso should not merge the information? @rtroncy 

Meanwhile, quick workaround: can you use `DISTINCT`? 😄

**Comment by delahousse** [comment] 2017-03-20 14:48
yes, yes we can use Distinct. We are just careful to send you comments when
we use the data.
jean

**Comment by rtroncy** [comment] 2017-03-20 23:31
> This can be caused by the fact that we load the info on the composer name twice: when we parse the artist file and when we find it as composer. Virtuoso should not merge the information? @rtroncy

Virtuoso does not do anything magic :-) RDF graphs are naturally merged when they share common nodes. We do have deterministic rules to mint URIs identifying nodes and that's why we can anticipate graphs merging at conversion time. Even if we load twice the same triple statement (?s ?p ?o), it will be present just once in the db.

I don't understand why you have twice the statement that an event is P14_carried_out_by an artist?

**Comment by pasqLisena** [comment] 2017-03-21 08:03
> I don't understand why you have twice the statement that an event is P14_carried_out_by an artist

No it is the `ecrm:P131_is_identified_by` that is present twice

**Comment by rtroncy** [comment] 2017-04-15 21:21
So, no, it is not present twice. Like I said, by definition, in a triple store, a triple is always unique. You can try to insert the same triple 10 times, it will be just present once in the knowledge base. However, Virtuoso is actually a quad store ... i.e., when you load data, you load data in a graph.

Slightly modified version of your query:
```
SELECT *
WHERE {
 graph ?g {
  ?b ecrm:P131_is_identified_by ?composer.
  filter (?composer = "Bach, Johann Sebastian (1685-1750)")
 }
}
```
The [results](http://data.doremus.org/sparql?default-graph-uri=&query=SELECT+*%0D%0AWHERE+%7B%0D%0A+graph+%3Fg+%7B%0D%0A++%3Fb+ecrm%3AP131_is_identified_by+%3Fcomposer.%0D%0A++filter+%28%3Fcomposer+%3D+%22Bach%2C+Johann+Sebastian+%281685-1750%29%22%29%0D%0A+%7D%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on) show you that you can see the composer in the BnF and Philharmonie graphs.

If you see duplicate, just add the graph and you will see that there are not true duplicates.

**Closed as completed by rtroncy** 2017-04-15 21:21 UTC
Labels: invalid
